replicaCount: 2

image:
  repository: 022267197315.dkr.ecr.ap-south-1.amazonaws.com/sample-war
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  path: /
  pathType: Prefix
